wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    code_path: code/experiments/sample_tracking.py
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1638256899
    t:
      4: 3.8.0
      5: 0.12.7
      8:
      - 5
